# Generated by Django 2.2.16 on 2020-10-04 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('acct_no', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('pin', models.PositiveSmallIntegerField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('pan', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=15)),
                ('mname', models.CharField(max_length=15)),
                ('lname', models.CharField(max_length=15)),
                ('date_birth', models.DateField()),
                ('address1', models.CharField(max_length=40)),
                ('address2', models.CharField(max_length=40)),
                ('address3', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='trans_info',
            fields=[
                ('trans_id', models.AutoField(max_length=12, primary_key=True, serialize=False)),
                ('trans_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cred_acct_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cred', to='bank.account')),
                ('deb_acct_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deb', to='bank.account')),
            ],
        ),
        migrations.CreateModel(
            name='cust_phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phno', models.CharField(max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.customer')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='customer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bank.customer'),
        ),
    ]
