# Generated by Django 2.2.16 on 2020-10-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='pin',
            field=models.PositiveIntegerField(),
        ),
    ]
